### ISSUE TITLE
Custom startup banner?

### ISSUE THREAD

**Issue by vojkog** [viadee/camunda-kafka-polling-client#13]
Do you think that for easier differentiation of multiple running (micro)services custom banner might be useful?

Example: https://github.com/moreECM/camunda-kafka-polling-client/blob/custom-banner/camunda-kafka-polling-client/src/main/resources/banner.txt

ASCI generator used: http://patorjk.com/software/taag/#p=display&h=1&f=Soft&t=VIADEE-CKPC

**Comment by MTwelkemeier** [comment]
From our perspective, it might not be necessary to identify a running instance, since this can be done using the existing features of the hosting technology. But if it useful for you, we can add a custom banner.

**Comment by vojkog** [comment]
For me, it is useful in development, but it is a more an idea then the issue. 
Should we close it?

**Comment by MTwelkemeier** [comment]
In general, it is a good idea. Currently, we can identify the instance using e.g. the instance name.
If you need it, we can add some custom banner. Otherwise, I agree to close this issue.

**Comment by MTwelkemeier** [comment]
Sorry - wrong issue number for commit 892ed396f6d88480f212928446f24b3773d8f05e
