### ISSUE TITLE
Error in pollProcessDefinitions

### ISSUE THREAD

**Issue by vojkog** [viadee/camunda-kafka-polling-client#19]
In JDBC profile I have a following error:
```
2019-03-05 10:10:46.693 ERROR 14348 --- [pool-2-thread-1] org.camunda.bpm.engine.bpmn.parser       : ENGINE-01004 Unexpected Exception with message: null 
2019-03-05 10:10:46.701 ERROR 14348 --- [pool-2-thread-1] org.camunda.bpm.engine.context           : ENGINE-16004 Exception while closing command context: ENGINE-01009 Error while parsing process. null.

org.camunda.bpm.engine.ProcessEngineException: ENGINE-01009 Error while parsing process. null.
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParseLogger.parsingProcessException(BpmnParseLogger.java:49) ~[camunda-engine-7.10.0.jar:7.10.0]
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParse.execute(BpmnParse.java:264) ~[camunda-engine-7.10.0.jar:7.10.0]
```
Environment: 
- camunda 7.10 (docker)
- mysql

It seems that in  [this line](https://github.com/viadee/camunda-kafka-polling-client/blob/881e2524444db10e148c3ae0ef05e1870a18ed4b/camunda-kafka-polling-client/src/main/java/de/viadee/camunda/kafka/pollingclient/service/polling/jdbc/CamundaJdbcPollingServiceImpl.java#L176)                 
`repositoryService.getProcessModel(processDefinition.getId())`

throws NPE in Camunda Source for HistoryParseListener.java because `historyLevel `is `null`.

```
  protected void addActivityHandlers(ActivityImpl activity) {
    if (historyLevel.isHistoryEventProduced(HistoryEventTypes.ACTIVITY_INSTANCE_START, null)) {
      activity.addBuiltInListener(PvmEvent.EVENTNAME_START, ACTIVITY_INSTANCE_START_LISTENER, 0);
    }
    if (historyLevel.isHistoryEventProduced(HistoryEventTypes.ACTIVITY_INSTANCE_END, null)) {
      activity.addBuiltInListener(PvmEvent.EVENTNAME_END, ACTIVITY_INSTANCE_END_LISTENER);
    }
  }
```

**Comment by vojkog** [comment]
.. it seems that the problem is related to `.setHistory(ProcessEngineConfiguration.HISTORY_AUTO)`.
It does not work on 7.10 (at least on my config.) as expected. When the historyLevel is as in the database e.g. `full`. there are no problems.

**Comment by MTwelkemeier** [comment]
That's interesting. The main idea regarding history level in jdbc polling is to ensure that no changes are made by the connecting engine. Configuration was made with the idea to use already configured history level available within the database.

**Comment by vojkog** [comment]
Yes, that is the purpose of the `HISTORY_AUTO` it seems that are some related issues are still open.
https://app.camunda.com/jira/browse/CAM-5164

**Comment by vojkog** [comment]
One idea, to avoid the current problem, is to leave `auto` as default and make historyLevel overridable via properties?
```
    @Value("${camunda.bpm.history-level:auto}")
    private String historyLevel;

   ..... 
   
    @Bean
    public ProcessEngine processEngine(DataSource dataSource) {
        return ProcessEngineConfiguration.createStandaloneProcessEngineConfiguration()
               ....
                .setHistory(historyLevel)
                .....
    }
```

**Comment by MTwelkemeier** [comment]
I agree - this seems to be the fastest way to avoid this issue. 

Regarding the configuration property I would always prefer using the Properties-Classes, since it provides at least a - more or less - central point where all configuration properties can be found. Even if those classes are spread all across the project, the annotation processor to generate the `spring-configuration-metadata.json` will find them all and provide a central documentation about available configuration properties.

**Comment by vojkog** [comment]
Here is a proposal with Prop.Class:
https://github.com/moreECM/camunda-kafka-polling-client/commit/9fb4642a32b2f795f418bc94fe6d2abe918cd3c7

**Comment by MTwelkemeier** [comment]
Merge request #24 has been manually merged.
