### ISSUE TITLE
Add MySQL dependency

### ISSUE THREAD

**Issue by MTwelkemeier** [viadee/camunda-kafka-polling-client#25]
Adding MySQL JDBC connector as dependency.

**Comment by MTwelkemeier** [comment]
This feature is currently pending due to license check

**Comment by vojkog** [comment]
I'm not an OSS licencing expert but it seems to me that BSD ("July 22 1999") is covered by "foss-exception": https://www.mysql.com/about/legal/licensing/foss-exception/ 

Versions after 8.0.4 with all "OSI-approved" licenses.

**Comment by MTwelkemeier** [comment]
Moved to next release, due to pending license check.

**Comment by MTwelkemeier** [comment]
Moved to release 1.2.0 to conform to semantic versioning, due to enhancement.

**Comment by MTwelkemeier** [comment]
With #30, docker image structure is modified. As a side effect, this might allow adding any additional jdbc driver by extending the docker image.

**Comment by vojkog** [comment]
As @MTwelkemeier have said, new docker image structure in #30 solves this issue elegantly so I suggest that we close my pull request #23 and this issue.

**Comment by MTwelkemeier** [comment]
@vojkog, sorry for legal clarification taking this long.
I think, having some default supported databases might be still a good enhancement. 
If you don't mind, I would suggest removing this issue from 1.2.0 roadmap but keep the option to add your merge request, once legal clarification is done.

**Comment by vojkog** [comment]
Of course. Thank you.

**Comment by MTwelkemeier** [comment]
Since there is a valid solution for using MySQL and other JDBC driver (extending the docker image), I would like to close this issue.
