### ISSUE TITLE
Add polling of identity link events

### ISSUE THREAD

**Issue by MTwelkemeier** [viadee/camunda-kafka-polling-client#34]
As suggested in issue #2, polling of identity link events should be added using REST and JDBC.

The are three different types of identity links available: 
* candidate
* assignee
* owner

Event data is available using REST and JDBC.

REST:
https://docs.camunda.org/manual/latest/reference/rest/history/identity-links/get-identity-link-query

JDBC:
`historyService.createHistoricIdentityLinkLogQuery().taskId(activityInstanceEvent.getTaskId()).list()`

**Comment by MTwelkemeier** [comment]
With `polling.polling-events`, there is a configuration, which allows to enable and disable polling of certain events. The three available link types might be handled as three configuration entries. This would allow a detailed selection of these events.
Maybe default should be disabled, to keep compatibility with existing setups.

**Comment by vojkog** [comment]
I like the idea. Is it too early if I draft some code in that direction next week?

**Comment by MTwelkemeier** [comment]
Thank you - if you have some draft, we can discuss some more details.

**Comment by vojkog** [comment]
Here is my initial impl. (for discussion).
https://github.com/moreECM/camunda-kafka-polling-client/commit/cd39b406926fbedb4f85b8b69034077c4206ace6
As you can see,  current impl. have only one enabler property.
I am looking forward to your comments.

**Comment by MTwelkemeier** [comment]
Great - I will take a look.

**Comment by MTwelkemeier** [comment]
Thank you for you contribution!

The impl already looks pretty complete. I added some ideas on given commit.
Regarding the single enabler property, I am not sure if it is possible to filter using more than one operation type during a single request. Thus, filtering more detailed might cause a lot of requests. I would vote to keep it with one property.

**Comment by vojkog** [comment]
Thank you! 
Regarding "the single enabler property" I agree that we keep only one.
I will look into your "in commit" comments.

**Comment by vojkog** [comment]
Hi @MTwelkemeier, I have included 2 of 3 of your comments in my last [commit](https://github.com/moreECM/camunda-kafka-polling-client/compare/cd39b406926f...c4bd2060c4ca). 
For the third one, I need some clarification. Please take a look at my responses to your "in commit" comments.

**Comment by MTwelkemeier** [comment]
I do agree, polling of identity links without task context might not the best approach.

As you pointed out: Current draft for polling of identity links works the same as e.g. polling variable events. As you described, this will result in polling the same identity link event multiple times.
I would suggest, to keep the task context as in you current draft, and also add the current polling timeslice start and end as request parameter to the polling. With this, we still have a single request and also respect the current timeslice to prevent polling the same event multiple times.
E.g. for the variable events, this has not been done due to the missing timestamp.

Just polling the links for finished tasks is also a viable solution. Since user tasks might be a long time in unfinished state, also polling links of these active tasks might provide a more "real time" event stream.

**Comment by vojkog** [comment]
Thank you @MTwelkemeier for clarifications.  I still do not get the idea of how to include current polling timeslice. If we pass the "task finish timeslice" we will skip identity-links with timestamp between "task start timeslice" and "task finish timeslice"?

**Comment by MTwelkemeier** [comment]
Sorry for being late, I was quite busy the last days:
My first idea was to just add the current timeslice start and end to the identity link filter: Thus, only identity links created within this timeslice are polled. Given a user task spreading three polling cycles, only the corresponding identity links created within each of these cycles would be polled.

Example:
```
Activity Start = T10
Identity Link A = T20
Identity Link B = T30
Identity Link C = T40
Activity End = T50

Polling Timeslice [T25...T35[

Polling Result is only "Identity Link B"
```

But: I just realized, activities are only polled twice. First as unfinished, as their creation time is within current polling timeslice and second as finished, with their end time is within current timeslice. Thus, we currently have no trigger to poll identity links of activities which have been started within past polling cycles but still listed as unfinished.

Adding such trigger might be a little more effort. Thus, I would agree to poll only with limitation to current activity, as in you current draft. If one would like to prevent duplicated events, polling might be limited to finished activities.

I think you idea to only poll links of finished events is the best approach:
Maybe we just split the configuration value for polling events (`IDENTITY_LINKS`) into two (`IDENTITY_LINKS_FINISHED_ACTIVITIES` and `IDENTITY_LINKS_UNFINISHED_ACTIVITIES`)? Thus, one can configure to only poll identity link events of finished activities (`IDENTITY_LINKS_FINISHED_ACTIVITIES`).

**Comment by vojkog** [comment]
Great! 
I like the idea of splitting the config value. Thx!

**Comment by vojkog** [comment]
Impl. with split config value is here: https://github.com/moreECM/camunda-kafka-polling-client/commit/9a4afbb9370d88572eb91225c6dd2ccd67d3f6a6

**Comment by MTwelkemeier** [comment]
Great - The enhancement looks pretty complete.
I would love to include this new feature. Could you provide a merge request for final review?
