### ISSUE TITLE
environment variable POLLING_RUNTIME_DATA_INITIAL_TIMESTAMP and POLLING_REPOSITORY_DATA_INITIAL_TIMESTAMP seem to be not working in 1.1.1

### ISSUE THREAD

**Issue by micudaj** [viadee/camunda-kafka-polling-client#36]
I tried to set environment variables
POLLING_RUNTIME_DATA_INITIAL_TIMESTAMP
POLLING_REPOSITORY_DATA_INITIAL_TIMESTAMP
in version 1.1.1 docker image, but it was not considered.
I set it in the format "2018-05-03 00:00:00".

**Comment by MTwelkemeier** [comment]
I checked providing the given properties, which worked fine. Maybe this is related to the changed packaging within the Docker image. I will do some additional tests.

**Comment by MTwelkemeier** [comment]
Cannot be reproduced
