### ISSUE TITLE
Resource instead of a xml-File works fine, if there is a parsing error in the xml

### ISSUE THREAD

**Issue by woldinius** [viadee/camunda-kafka-polling-client#40]
https://github.com/viadee/camunda-kafka-polling-client/blob/acb003d06e02732ae50b84e3438e55b8a58edd54/camunda-kafka-polling-client/src/main/java/de/viadee/camunda/kafka/pollingclient/service/polling/jdbc/CamundaJdbcPollingServiceImpl.java#L203

**Comment by MTwelkemeier** [comment]
First draft created with https://github.com/viadee/camunda-kafka-polling-client/commit/acb003d06e02732ae50b84e3438e55b8a58edd54

**Comment by MTwelkemeier** [comment]
Does this fix work for you, so we can close the issue?
