### ISSUE TITLE
"LastPolled" timestamps are updated even when data could not be sent to Kafka

### ISSUE THREAD

**Issue by jfriedenstab** [viadee/camunda-kafka-polling-client#41]
Currently, the polling client updates the lastPolled timestamps for runtime and repository data even when data could not be sent to Kafka, e.g. when Kafka is not available. This leads to data loss.
The timestamps should only be updated if all data requested from Camunda has been successfully sent to Kafka.

**Comment by jfriedenstab** [comment]
For example, when you stop Kafka while the polling client is running, you see the following behavior:

> [Producer clientId=camunda-kafka-polling-client] Connection to node 1 could not be established. Broker may not be available.
[Producer clientId=camunda-kafka-polling-client] Connection to node 1 could not be established. Broker may not be available.
Start polling runtime data: PollingTimeslice(cutoffTime=2000-01-01 00:00:00.000, startTime=2019-09-10 09:27:58.353, endTime=2019-09-10 09:28:28.686)
Set lastPolled to Tue Sep 10 09:28:28 CEST 2019
Set cutoff to Sat Jan 01 00:00:00 CET 2000
Finished polling runtime data: PollingTimeslice(cutoffTime=2000-01-01 00:00:00.000, startTime=2019-09-10 09:27:58.353, endTime=2019-09-10 09:28:28.686)
[Producer clientId=camunda-kafka-polling-client] Connection to node 1 could not be established. Broker may not be available.
[Producer clientId=camunda-kafka-polling-client] Connection to node 1 could not be established. Broker may not be available.
...
[Producer clientId=camunda-kafka-polling-client] Connection to node 1 could not be established. Broker may not be available.
[Producer clientId=camunda-kafka-polling-client] Connection to node 1 could not be established. Broker may not be available.
Start polling repository data: PollingTimeslice(cutoffTime=2000-01-01 00:00:00.000, startTime=2019-09-10 09:28:25.685, endTime=2019-09-10 09:28:55.696)
Set lastPolled to Tue Sep 10 09:28:55 CEST 2019
Set cutoff to Sat Jan 01 00:00:00 CET 2000
Finished polling repository data: PollingTimeslice(cutoffTime=2000-01-01 00:00:00.000, startTime=2019-09-10 09:28:25.685, endTime=2019-09-10 09:28:55.696)
[Producer clientId=camunda-kafka-polling-client] Connection to node 1 could not be established. Broker may not be available.
[Producer clientId=camunda-kafka-polling-client] Connection to node 1 could not be established. Broker may not be available.

**Comment by MTwelkemeier** [comment]
There is no exception thrown on sending the event using `KafkaTemplate`. To retrieve the result we should add a `get()` call on the given `Future`:

https://github.com/viadee/camunda-kafka-polling-client/blob/133e0e6568fd5e77c6a1f15f003660c3f5015fdd/camunda-kafka-polling-client/src/main/java/de/viadee/camunda/kafka/pollingclient/service/event/kafka/KafkaEventServiceImpl.java#L55

and

https://github.com/viadee/camunda-kafka-polling-client/blob/133e0e6568fd5e77c6a1f15f003660c3f5015fdd/camunda-kafka-polling-client/src/main/java/de/viadee/camunda/kafka/pollingclient/service/event/kafka/KafkaEventServiceImpl.java#L67

Maybe we should make the time to wait configurable to prevent infinite waiting.
