### ISSUE TITLE
Bring all dep's up to date

### ISSUE THREAD

**Issue by fkoehne** [viadee/camunda-kafka-polling-client#8]
Esp. com.fasterxml.jackson.core:jackson-databind ~> 2.9.8.

**Comment by micudaj** [comment]
@fkoehne  com.fasterxml.jackson.core:jackson-databind is on 2.9.8. Anything more required?

**Comment by vojkog** [comment]
Should we upgrade Camunda dependencies to the latest release (7.10.0)? 
On my machine 7.10.0 works fine with REST profile, with JDBC I have issue #19.

**Comment by vojkog** [comment]
To parallel [docker-camunda](https://github.com/camunda/docker-camunda-bpm-platform):

> The docker image already contains drivers for h2, mysql and postgresql. 

 maybe we should add MySQL runtime dependency?

**Comment by fkoehne** [comment]
@vojkog, that sounds good to me - both ideas. 
@micudaj, I didn't think of anything else in particular.
@MTwelkemeier , what do you think?

**Comment by MTwelkemeier** [comment]
I think so, too. Regarding update of Camunda we might need to keep an eye on version compatibility.

**Comment by vojkog** [comment]
MySQL deps. and latest camunda upgrade went well:
- https://github.com/moreECM/camunda-kafka-polling-client/commit/26f0f575ec1f290c1215e9c9c78348948f45a976
- https://github.com/moreECM/camunda-kafka-polling-client/commit/e2836b9eecd73d4c2aa811b60c58079c24088e84

**Comment by MTwelkemeier** [comment]
With merge request #24, dependency of Camunda has been raised to 7.10.0.
